# Définition d'un tableau de routes au format TOML (https://toml.io/)
# - url : chemin dans l'URL
# - controleur : chemin vers le fichier du controleur
# - template : chemin vers le fichier de template
#controleur = "controleurs/grille_pygame.py"


[[routes]]
url = ""
controleur = "controleurs/accueil.py"
template = "accueil.html"

[[routes]]
url = "statistiques"
controleur = "controleurs/statistiques.py"
template = "statistiques.html"

[[routes]]
url = "grille"
controleur = "controleurs/grille.py"
template = "grille.html"

[[routes]]
url = "pioche"
controleur = "controleurs/pioche.py"
template = "pioche.html"

[[routes]]
url = "submit_choice"
controleur = "controleurs/pioche.py"
template = "pioche.html"










